"""Second  migration

Revision ID: 70acbc903fe4
Revises: 5a75c455b0b9
Create Date: 2026-09-18 22:15:27.517303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70acbc903fe4'
down_revision: Union[str, Sequence[str], None] = '5a75c455b0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE product_status ADD VALUE 'deprecated' AFTER 'archived'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS product_status_fake CASCADE")
    op.execute("UPDATE products SET status = 'draft' WHERE status = 'deprecated'")
    op.execute("ALTER TYPE product_status RENAME TO product_status_fake")
    op.execute("CREATE TYPE product_status AS ENUM ('draft', 'published', 'archived')")
    op.execute("""
            ALTER TABLE products 
            ALTER COLUMN status DROP DEFAULT,
            ALTER COLUMN status TYPE product_status 
            USING status::text::product_status,
            ALTER COLUMN status 
            SET DEFAULT 'draft'::product_status
        """)
    op.execute("DROP TYPE product_status_fake")
    # ### end Alembic commands ###
