"""First  migration

Revision ID: eeace12917ce
Revises: 
Create Date: 2026-09-09 13:06:26.307890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeace12917ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    product_status = sa.Enum('draft', 'published', 'archived', name='product_status')
    product_status.create(op.get_bind(), checkfirst=True)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('5_3_2', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('5_3_2', sa.Column('title', sa.String(), nullable=False))
    op.add_column('5_3_2', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('5_3_2', sa.Column('count', sa.Integer(), nullable=False))
    op.add_column('5_3_2', sa.Column('description', sa.String(), server_default='', nullable=False))
    op.add_column('5_3_2', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='product_status'), server_default='draft', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('5_3_2', 'status')
    op.drop_column('5_3_2', 'description')
    op.drop_column('5_3_2', 'count')
    op.drop_column('5_3_2', 'price')
    op.drop_column('5_3_2', 'title')
    op.drop_column('5_3_2', 'id')
    # ### end Alembic commands ###
