"""Second  migration

Revision ID: f52ef5009e88
Revises: eeace12917ce
Create Date: 2026-09-09 13:07:42.659867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52ef5009e88'
down_revision: Union[str, Sequence[str], None] = 'eeace12917ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE product_status ADD VALUE 'deprecated'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE product_status RENAME TO product_status_old")
    op.execute("CREATE TYPE product_status AS ENUM('draft', 'published', 'archived')")
    op.execute("ALTER TABLE product ALTER status DROP DEFAULT")
    op.execute("ALTER TABLE product ALTER COLUMN status TYPE product_status USING status::text::product_status DEFAULT 'draft'")
    op.execute("UPDATE product SET product_status = 'draft' WHERE product = 'deprecated'")
    op.execute("DROP TYPE product_status_old")
    # ### end Alembic commands ###
