"""First  migration

Revision ID: 5a75c455b0b9
Revises: 
Create Date: 2026-09-18 22:13:38.082215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a75c455b0b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        '5_3_2',
        sa.Column('id', sa.Integer(), autoincrement=True, primary_key=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('count', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), server_default='', nullable=False),
        sa.Column(
            'status',
            sa.Enum('draft', 'published', 'archived', name='product_status'),
            server_default='draft',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('5_3_2')
    op.execute('DROP TYPE IF EXISTS product_status')
    # ### end Alembic commands ###