"""Second  migration

Revision ID: 17342cc750c6
Revises: cd5245cf069f
Create Date: 2026-08-30 19:29:43.849823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17342cc750c6'
down_revision: Union[str, Sequence[str], None] = 'cd5245cf069f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('5_3_1', sa.Column('description', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('5_3_1', 'description')
    # ### end Alembic commands ###
