"""Second  migration

Revision ID: 6e927ce0ba0e
Revises: fee2e87fa849
Create Date: 2026-09-02 14:49:08.121623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e927ce0ba0e'
down_revision: Union[str, Sequence[str], None] = 'fee2e87fa849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('5_3_1', sa.Column('description', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('5_3_1', 'description')
    # ### end Alembic commands ###
